[package]
name = "crates-lsp"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = "0.3.17"

tokio = { version = "1.29.1", features = ["rt", "macros", "io-std"] }
tower-lsp = "0.19.0"

semver = { version = "1", features = ["serde"] }
hyper = { version = "0.14.27", features = ["client", "http1"] }
hyper-rustls = "0.24.1"
serde_json = "1.0.104"
serde = { version = "1.0.180", features = ["derive"] }

[dev-dependencies]
indoc = "2"
